### ISSUE TITLE
i want to add a cat gif ; will it be considered for hactober and what are the guidelines for as succesful PR

### ISSUE THREAD

**Issue by Ashutosh-Panda** [ChristianECG/TheBestCatPage#18]

**Comment by nightlark** [comment]
It seems like this repo was created to get easy +1 PRs, which would go against the spirit of Hacktoberfest. I wouldn't be surprised if it gets blocked and PRs to it don't count.

**Comment by Ashutosh-Panda** [comment]
> It seems like this repo was created to get easy +1 PRs, which would go against the spirit of Hacktoberfest. I wouldn't be surprised if it gets blocked and PRs to it don't count.

i found this in the discord of hacktober as a beginner friendly repo; being my first repo i was excited to commit. what should i do any advice??
