### ISSUE TITLE
Add a custom scrollbar 

### ISSUE THREAD

**Issue by priyaastha** [ChristianECG/TheBestCatPage#40]
I would like to add a custom scrollbar. @ChristianECG please assign this to me under hactoberfest.

**Comment by ChristianECG** [comment]
Ok, cool. Do it!

**Comment by priyaastha** [comment]
@ChristianECG sir please review and merge my PR. My PR number is #43 . Thank you.

**Comment by ChristianECG** [comment]
Thx!
